name: Android CI

on:
  push:
    branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Free disk space
              run: |
                  sudo rm -rf /usr/share/dotnet
                  sudo rm -rf /usr/local/lib/android/sdk/ndk
                  sudo rm -rf /usr/local/lib/android/sdk/build-tools/3[0-2]*
                  sudo rm -rf /opt/ghc
                  sudo rm -rf /opt/hostedtoolcache/CodeQL
                  df -h

            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  distribution: "zulu" # Options: zulu, temurin, adopt, etc.
                  java-version: "17"
                  cache: "gradle" # Automatically caches Gradle dependencies

            - name: Grant execute permission for gradlew
              run: chmod +x gradlew

            - name: Run unit tests
              run: ./gradlew testDebugUnitTest --stacktrace

            - name: Build with Gradle
              run: ./gradlew assembleDebug --stacktrace

            - name: Upload APK Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: android-debug-apk
                  path: app/build/outputs/apk/debug/app-debug.apk
                  retention-days: 42 # Optional: Defaults to 90 days
